version: 2

project_name: ugh

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: ugh
    main: .
    binary: ugh
    ldflags:
      - -s -w
      - -X github.com/mholtzscher/ugh/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

brews:
  - name: ugh
    repository:
      owner: mholtzscher
      name: homebrew-tap
      token: "{{ .Env.PAT }}"
    directory: Formula
    homepage: "https://github.com/mholtzscher/ugh"
    description: "A GTD-first task CLI with SQLite storage."
    license: "MIT"
    install: |
      bin.install "ugh"
    test: |
      system "#{bin}/ugh", "--version"

release:
  github:
    owner: mholtzscher
    name: ugh
  prerelease: auto
  name_template: "v{{.Version}}"

