// Code generated by "stringer -type=Field,PredicateKind,TargetKind,TagKind,FilterBoolOp -output=ast_string.go"; DO NOT EDIT.

package nlp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldTitle-0]
	_ = x[FieldNotes-1]
	_ = x[FieldDue-2]
	_ = x[FieldWaiting-3]
	_ = x[FieldState-4]
	_ = x[FieldProjects-5]
	_ = x[FieldContexts-6]
	_ = x[FieldMeta-7]
}

const _Field_name = "FieldTitleFieldNotesFieldDueFieldWaitingFieldStateFieldProjectsFieldContextsFieldMeta"

var _Field_index = [...]uint8{0, 10, 20, 28, 40, 50, 63, 76, 85}

func (i Field) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Field_index)-1 {
		return "Field(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Field_name[_Field_index[idx]:_Field_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PredState-0]
	_ = x[PredDue-1]
	_ = x[PredProject-2]
	_ = x[PredContext-3]
	_ = x[PredText-4]
	_ = x[PredID-5]
}

const _PredicateKind_name = "PredStatePredDuePredProjectPredContextPredTextPredID"

var _PredicateKind_index = [...]uint8{0, 9, 16, 27, 38, 46, 52}

func (i PredicateKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PredicateKind_index)-1 {
		return "PredicateKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PredicateKind_name[_PredicateKind_index[idx]:_PredicateKind_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TargetSelected-0]
	_ = x[TargetID-1]
}

const _TargetKind_name = "TargetSelectedTargetID"

var _TargetKind_index = [...]uint8{0, 14, 22}

func (i TargetKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TargetKind_index)-1 {
		return "TargetKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TargetKind_name[_TargetKind_index[idx]:_TargetKind_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TagProject-0]
	_ = x[TagContext-1]
}

const _TagKind_name = "TagProjectTagContext"

var _TagKind_index = [...]uint8{0, 10, 20}

func (i TagKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TagKind_index)-1 {
		return "TagKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TagKind_name[_TagKind_index[idx]:_TagKind_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterAnd-0]
	_ = x[FilterOr-1]
}

const _FilterBoolOp_name = "FilterAndFilterOr"

var _FilterBoolOp_index = [...]uint8{0, 9, 17}

func (i FilterBoolOp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FilterBoolOp_index)-1 {
		return "FilterBoolOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterBoolOp_name[_FilterBoolOp_index[idx]:_FilterBoolOp_index[idx+1]]
}
