// Code generated by "stringer -type=Field -trimprefix=Field -output=ast_field_string.go"; DO NOT EDIT.

package nlp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldTitle-0]
	_ = x[FieldNotes-1]
	_ = x[FieldDue-2]
	_ = x[FieldWaiting-3]
	_ = x[FieldState-4]
	_ = x[FieldProjects-5]
	_ = x[FieldContexts-6]
	_ = x[FieldMeta-7]
}

const _Field_name = "TitleNotesDueWaitingStateProjectsContextsMeta"

var _Field_index = [...]uint8{0, 5, 10, 13, 20, 25, 33, 41, 45}

func (i Field) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Field_index)-1 {
		return "Field(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Field_name[_Field_index[idx]:_Field_index[idx+1]]
}
