// Code generated by participle grammar. DO NOT EDIT.

package nlp

import (
	"github.com/alecthomas/participle/v2"
)

// GInput represents a flat sequence of DSL tokens
type GInput struct {
	Verb   string    `parser:"@Verb"`
	Tokens []*GToken `parser:"@@*"`
}

type GToken struct {
	Ident      string `parser:"@Ident"`
	Quoted     string `parser:"| @Quoted"`
	Colon      string `parser:"| @Colon"`
	Verb       string `parser:"| @Verb"`
	AddOp      string `parser:"| @AddOp"`
	RemoveOp   string `parser:"| @RemoveOp"`
	ClearOp    string `parser:"| @ClearOp"`
	ProjectTag string `parser:"| @ProjectTag"`
	ContextTag string `parser:"| @ContextTag"`
	LParen     string `parser:"| @LParen"`
	RParen     string `parser:"| @RParen"`
	AndOp      string `parser:"| @AndOp"`
	OrOp       string `parser:"| @OrOp"`
	And        string `parser:"| @And"`
	Or         string `parser:"| @Or"`
	Not        string `parser:"| @Not"`
}

var dslParser = participle.MustBuild[GInput](
	participle.Lexer(dslLexer),
	participle.Elide("Whitespace"),
	participle.Unquote("Quoted"),
)
