// Code generated by "stringer -type=Mode,Intent,Severity -output=types_string.go"; DO NOT EDIT.

package nlp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeAuto-0]
	_ = x[ModeCreate-1]
	_ = x[ModeUpdate-2]
	_ = x[ModeFilter-3]
	_ = x[ModeView-4]
	_ = x[ModeContext-5]
}

const _Mode_name = "ModeAutoModeCreateModeUpdateModeFilterModeViewModeContext"

var _Mode_index = [...]uint8{0, 8, 18, 28, 38, 46, 57}

func (i Mode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Mode_index)-1 {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[idx]:_Mode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IntentUnknown-0]
	_ = x[IntentCreate-1]
	_ = x[IntentUpdate-2]
	_ = x[IntentFilter-3]
	_ = x[IntentView-4]
	_ = x[IntentContext-5]
	_ = x[IntentLog-6]
}

const _Intent_name = "IntentUnknownIntentCreateIntentUpdateIntentFilterIntentViewIntentContextIntentLog"

var _Intent_index = [...]uint8{0, 13, 25, 37, 49, 59, 72, 81}

func (i Intent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Intent_index)-1 {
		return "Intent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Intent_name[_Intent_index[idx]:_Intent_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeverityError-0]
	_ = x[SeverityWarning-1]
	_ = x[SeverityInfo-2]
}

const _Severity_name = "SeverityErrorSeverityWarningSeverityInfo"

var _Severity_index = [...]uint8{0, 13, 28, 40}

func (i Severity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Severity_index)-1 {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[idx]:_Severity_index[idx+1]]
}
