// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearShellHistory = `-- name: ClearShellHistory :exec
DELETE FROM shell_history
`

func (q *Queries) ClearShellHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearShellHistory)
	return err
}

const insertShellHistory = `-- name: InsertShellHistory :one
INSERT INTO shell_history (
  timestamp,
  command,
  success,
  result_summary,
  intent
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING
  id,
  timestamp,
  command,
  success,
  result_summary,
  intent
`

type InsertShellHistoryParams struct {
	Timestamp     int64          `json:"timestamp"`
	Command       string         `json:"command"`
	Success       bool           `json:"success"`
	ResultSummary sql.NullString `json:"result_summary"`
	Intent        sql.NullString `json:"intent"`
}

func (q *Queries) InsertShellHistory(ctx context.Context, arg InsertShellHistoryParams) (ShellHistory, error) {
	row := q.db.QueryRowContext(ctx, insertShellHistory,
		arg.Timestamp,
		arg.Command,
		arg.Success,
		arg.ResultSummary,
		arg.Intent,
	)
	var i ShellHistory
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Command,
		&i.Success,
		&i.ResultSummary,
		&i.Intent,
	)
	return i, err
}

const listShellHistory = `-- name: ListShellHistory :many
SELECT
  id,
  timestamp,
  command,
  success,
  result_summary,
  intent
FROM shell_history
ORDER BY timestamp DESC
LIMIT ?
`

func (q *Queries) ListShellHistory(ctx context.Context, limit int64) ([]ShellHistory, error) {
	rows, err := q.db.QueryContext(ctx, listShellHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShellHistory
	for rows.Next() {
		var i ShellHistory
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Command,
			&i.Success,
			&i.ResultSummary,
			&i.Intent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchShellHistory = `-- name: SearchShellHistory :many
SELECT
  id,
  timestamp,
  command,
  success,
  result_summary,
  intent
FROM shell_history
WHERE (
  ? IS NULL OR command LIKE '%' || ? || '%'
)
  AND (? IS NULL OR intent = ?)
  AND (? IS NULL OR success = ?)
ORDER BY timestamp DESC
LIMIT ?
`

type SearchShellHistoryParams struct {
	Column1 interface{}    `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
	Column3 interface{}    `json:"column_3"`
	Intent  sql.NullString `json:"intent"`
	Column5 interface{}    `json:"column_5"`
	Success bool           `json:"success"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) SearchShellHistory(ctx context.Context, arg SearchShellHistoryParams) ([]ShellHistory, error) {
	rows, err := q.db.QueryContext(ctx, searchShellHistory,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Intent,
		arg.Column5,
		arg.Success,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShellHistory
	for rows.Next() {
		var i ShellHistory
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Command,
			&i.Success,
			&i.ResultSummary,
			&i.Intent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShellHistory = `-- name: UpdateShellHistory :exec
UPDATE shell_history
SET
  success = ?,
  result_summary = ?,
  intent = ?
WHERE id = ?
`

type UpdateShellHistoryParams struct {
	Success       bool           `json:"success"`
	ResultSummary sql.NullString `json:"result_summary"`
	Intent        sql.NullString `json:"intent"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateShellHistory(ctx context.Context, arg UpdateShellHistoryParams) error {
	_, err := q.db.ExecContext(ctx, updateShellHistory,
		arg.Success,
		arg.ResultSummary,
		arg.Intent,
		arg.ID,
	)
	return err
}
