// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Context struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Project struct {
	ID         int64         `json:"id"`
	Name       string        `json:"name"`
	Notes      string        `json:"notes"`
	ArchivedAt sql.NullInt64 `json:"archived_at"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
}

type Task struct {
	ID          int64          `json:"id"`
	State       string         `json:"state"`
	PrevState   sql.NullString `json:"prev_state"`
	Priority    sql.NullString `json:"priority"`
	Title       string         `json:"title"`
	Notes       string         `json:"notes"`
	DueOn       sql.NullString `json:"due_on"`
	WaitingFor  sql.NullString `json:"waiting_for"`
	CompletedAt sql.NullInt64  `json:"completed_at"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type TaskContextLink struct {
	TaskID    int64 `json:"task_id"`
	ContextID int64 `json:"context_id"`
}

type TaskMetum struct {
	TaskID int64  `json:"task_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

type TaskProjectLink struct {
	TaskID    int64 `json:"task_id"`
	ProjectID int64 `json:"project_id"`
}
