// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Task struct {
	ID             int64          `json:"id"`
	Done           int64          `json:"done"`
	Priority       sql.NullString `json:"priority"`
	CompletionDate sql.NullString `json:"completion_date"`
	CreationDate   sql.NullString `json:"creation_date"`
	Description    interface{}    `json:"description"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

type TaskContext struct {
	TaskID int64  `json:"task_id"`
	Name   string `json:"name"`
}

type TaskMetum struct {
	TaskID int64  `json:"task_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

type TaskProject struct {
	TaskID int64  `json:"task_id"`
	Name   string `json:"name"`
}

type TaskUnknown struct {
	TaskID  int64  `json:"task_id"`
	Ordinal int64  `json:"ordinal"`
	Token   string `json:"token"`
}
