// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type ShellHistory struct {
	ID            int64          `json:"id"`
	Timestamp     int64          `json:"timestamp"`
	Command       string         `json:"command"`
	Success       bool           `json:"success"`
	ResultSummary sql.NullString `json:"result_summary"`
	Intent        sql.NullString `json:"intent"`
}

type Task struct {
	ID        int64 `json:"id"`
	CreatedAt int64 `json:"created_at"`
}

type TaskVersion struct {
	VersionID    int64          `json:"version_id"`
	TaskID       int64          `json:"task_id"`
	State        string         `json:"state"`
	PrevState    sql.NullString `json:"prev_state"`
	Title        string         `json:"title"`
	Notes        string         `json:"notes"`
	DueOn        sql.NullString `json:"due_on"`
	WaitingFor   sql.NullString `json:"waiting_for"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
	UpdatedAt    int64          `json:"updated_at"`
	Deleted      int64          `json:"deleted"`
	ProjectsJson string         `json:"projects_json"`
	ContextsJson string         `json:"contexts_json"`
	MetaJson     string         `json:"meta_json"`
}

type TasksCurrent struct {
	ID           int64          `json:"id"`
	State        string         `json:"state"`
	PrevState    sql.NullString `json:"prev_state"`
	Title        string         `json:"title"`
	Notes        string         `json:"notes"`
	DueOn        sql.NullString `json:"due_on"`
	WaitingFor   sql.NullString `json:"waiting_for"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	ProjectsJson string         `json:"projects_json"`
	ContextsJson string         `json:"contexts_json"`
	MetaJson     string         `json:"meta_json"`
	VersionID    int64          `json:"version_id"`
}
