// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertTaskEvent = `-- name: InsertTaskEvent :one
INSERT INTO task_events (
  task_id,
  timestamp,
  kind,
  summary,
  changes_json,
  origin,
  shell_history_id
) VALUES (
  ?, ?, ?, ?, ?, ?, ?
)
RETURNING
  id,
  task_id,
  timestamp,
  kind,
  summary,
  changes_json,
  origin,
  shell_history_id
`

type InsertTaskEventParams struct {
	TaskID         int64          `json:"task_id"`
	Timestamp      int64          `json:"timestamp"`
	Kind           string         `json:"kind"`
	Summary        sql.NullString `json:"summary"`
	ChangesJson    sql.NullString `json:"changes_json"`
	Origin         sql.NullString `json:"origin"`
	ShellHistoryID sql.NullInt64  `json:"shell_history_id"`
}

func (q *Queries) InsertTaskEvent(ctx context.Context, arg InsertTaskEventParams) (TaskEvent, error) {
	row := q.db.QueryRowContext(ctx, insertTaskEvent,
		arg.TaskID,
		arg.Timestamp,
		arg.Kind,
		arg.Summary,
		arg.ChangesJson,
		arg.Origin,
		arg.ShellHistoryID,
	)
	var i TaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Timestamp,
		&i.Kind,
		&i.Summary,
		&i.ChangesJson,
		&i.Origin,
		&i.ShellHistoryID,
	)
	return i, err
}

const listTaskEventsByTaskID = `-- name: ListTaskEventsByTaskID :many
SELECT
  te.id,
  te.task_id,
  te.timestamp,
  te.kind,
  te.summary,
  te.changes_json,
  te.origin,
  te.shell_history_id,
  sh.command AS shell_command
FROM task_events te
LEFT JOIN shell_history sh ON sh.id = te.shell_history_id
WHERE te.task_id = ?
ORDER BY te.timestamp DESC, te.id DESC
LIMIT ?
`

type ListTaskEventsByTaskIDParams struct {
	TaskID int64 `json:"task_id"`
	Limit  int64 `json:"limit"`
}

type ListTaskEventsByTaskIDRow struct {
	ID             int64          `json:"id"`
	TaskID         int64          `json:"task_id"`
	Timestamp      int64          `json:"timestamp"`
	Kind           string         `json:"kind"`
	Summary        sql.NullString `json:"summary"`
	ChangesJson    sql.NullString `json:"changes_json"`
	Origin         sql.NullString `json:"origin"`
	ShellHistoryID sql.NullInt64  `json:"shell_history_id"`
	ShellCommand   sql.NullString `json:"shell_command"`
}

func (q *Queries) ListTaskEventsByTaskID(ctx context.Context, arg ListTaskEventsByTaskIDParams) ([]ListTaskEventsByTaskIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskEventsByTaskID, arg.TaskID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskEventsByTaskIDRow
	for rows.Next() {
		var i ListTaskEventsByTaskIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Timestamp,
			&i.Kind,
			&i.Summary,
			&i.ChangesJson,
			&i.Origin,
			&i.ShellHistoryID,
			&i.ShellCommand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
