package flags

const (
	FlagAll           = "all"
	FlagCompleted     = "completed"
	FlagConfigPath    = "config"
	FlagContext       = "context"
	FlagCounts        = "counts"
	FlagCreated       = "created"
	FlagDBPath        = "db"
	FlagDescription   = "description"
	FlagTitle         = "title"
	FlagDone          = "done"
	FlagEditor        = "editor"
	FlagFormat        = "format"
	FlagJSON          = "json"
	FlagLines         = "lines"
	FlagMeta          = "meta"
	FlagNotes         = "notes"
	FlagNoColor       = "no-color"
	FlagNoFollow      = "no-follow"
	FlagNoDue         = "no-due"
	FlagNoWaitingFor  = "no-waiting-for"
	FlagProject       = "project"
	FlagRemoveContext = "remove-context"
	FlagRemoveMeta    = "remove-meta"
	FlagRemoveProject = "remove-project"
	FlagSearch        = "search"
	FlagState         = "state"
	FlagTodo          = "todo"
	FlagUndone        = "undone"
	FlagDueOn         = "due"
	FlagWaitingFor    = "waiting-for"
)
